apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-mysql
  template:
    metadata:
      labels:
        app: ems-mysql
    spec:
      containers:
        - name: ems-mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ems123
            - name: MYSQL_DATABASE
              value: ems
---
apiVersion: v1
kind: Service
metadata:
  name: ems-mysql
spec:
  selector:
    app: ems-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
